### ISSUE TITLE
Missing FLUTTER_ROOT results in hard-to-debug error.

### ISSUE THREAD

**Issue by ghost** [jonahwilliams/tester#113]
The first few times trying to use tester I got the following:
```bash
$ pushd packages/flutter_tools  ;  ../../bin/cache/dart-sdk/bin/pub global run tester -j2 -v --ci --timeout=15 test/general.shard  ;  popd
Unhandled exception:
Invalid argument(s): join(null, "bin/cache/dart-sdk/lib/dev_compiler/kernel/amd/require.js"): part 0 was null, but part 1 was not.
#0      _validateArgList (package:path/src/context.dart:1101:5)
#1      Context.join (package:path/src/context.dart:240:5)
#2      new Config (package:tester/src/config.dart:129:34)
#3      main (package:tester/src/executable.dart:162:16)
#4      main (file:///[...]/.pub-cache/hosted/pub.dartlang.org/tester-0.0.2-dev7/bin/tester.dart:8:10)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

The warning in the README eventually tipped me off to set `FLUTTER_ROOT` which solved the issue:
https://github.com/jonahwilliams/tester/blob/e30adb3d8de2b93be19ff349d829b1679412d3f4/README.md#L7

I think it would be good to handle this error case a bit more gracefully by detecting when the path isn't set and print a similar notice to that found in the README.

**Comment by jonahwilliams** [comment]
Yeah, the environment setup is a bit of a mess right now. The runner should know if it was able to locate the flutter SDK or not, and if a flutter env was requested we could print an error message instead, suggesting FLUTTER_ROOT
